### ISSUE TITLE
Queue/Exchange declaration

### ISSUE THREAD

**Issue by FabioBatSilva** [instaclick/PDI-Plugin-Step-AMQP#4]
This plugin should be able to create Queue and Exchange

Basic options : 
* durable (check box)
* auto-delete (check box)

Queue options : 
* binding (Table)

**Comment by dshvedchenko** [comment]
@FabioBatSilva 
I can start with adding
- Boolean : Declare - true for adding objects and Binding
- split Exchange and Queue name
- add Exchange type
- add Durability
- add auto-delete

For consumer mode when Declare/Binding is _on_:
new Table is needed:
- Exchange name
- Routing Key

**Comment by FabioBatSilva** [comment]
@dshvedchenko Sounds good, let me know if you need any help..

**Comment by dshvedchenko** [comment]
@FabioBatSilva , please, review my requests.
I'm using Binding tables for both Producer and COnsumer, ignoring Exchange type column for Binding Exchange to QUeues

**Comment by FabioBatSilva** [comment]
@dshvedchenko Cool !!

I'll take a look

**Comment by dshvedchenko** [comment]
@FabioBatSilva 
Added to Binding table type of target, to allow bind Exchange to Exchange.
Added waiting consumer option

**Comment by FabioBatSilva** [comment]
@dshvedchenko I'll check it out soon..

**Comment by FabioBatSilva** [comment]
Fixed by : https://github.com/instaclick/PDI-Plugin-Step-AMQP/pull/10
